# Basic pipeline for the project.
stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job: # This job runs in the build stage, which runs first with docker compose.
  stage: build
  image: docker:latest
  before_script:
    - docker info
    - docker-compose -v
  script:
    - echo "Setting up environment with Docker Compose"
    - docker-compose -f docker-compose.yaml up -d # Start services in detached mode

api-test-job: # This job runs in the test stage.
  image: docker:latest
  stage: test # It only starts when the job in the build stage completes successfully.
  before_script:
    - apk add --no-cache curl # Install curl for Alpine-based images (docker:latest uses Alpine)
    - sleep 10
    - docker-compose ps
    - curl http://127.0.0.1:8197
    - sleep 10
    - curl -i http://127.0.0.1:8197/state
  script:
    - echo "Running api tests..."
    - python3 tests/api_tests.py # Try running the test script

deploy-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
