# Basic pipeline for the project.
stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job: # This job runs in the build stage, which runs first with docker compose.
  stage: build
  before_script:
    - apt-get update && apt-get install -y docker.io docker-compose sudo python3-requests # Install Docker and Docker Compose
    - sudo systemctl start docker
    - docker info
  script:
    - echo "Setting up environment with Docker Compose"
    - docker-compose -f docker-compose.yaml up -d # Start services in detached mode

api-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running api tests..."
    - docker-compose ps

deploy-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
