# Basic pipeline for the project.
stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job: # This job runs in the build stage, which runs first with docker compose.
  stage: build
  image: docker:latest
  before_script:
    - docker info
    - docker-compose -v
  script:
    - echo "Setting up environment with Docker Compose"
    - docker-compose -f docker-compose.yaml up -d # Start services in detached mode

api-test-job: # This job runs in the test stage.
  image: python:3.11-slim
  stage: test # It only starts when the job in the build stage completes successfully.
  before_script:
    - apk add --no-cache curl python3 docker docker-compose py3-pip # Install curl for Alpine-based images (docker:latest uses Alpine)
    - sleep 10
    - docker-compose ps
    - DOCKER_HOST_IP=$(docker network inspect bridge --format '{{range .IPAM.Config}}{{.Gateway}}{{end}}')
    - export DOCKER_HOST_IP
    - curl http://$DOCKER_HOST_IP:8197
    - sleep 10
    - curl -X PUT -d "RUNNING" http://$DOCKER_HOST_IP:8197/state
  script:
    - echo "Running api tests..."
    - python3 tests/api_tests.py # Try running the test script

deploy-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  image: docker:latest
  script:
    - echo "Deploying application..."
    - docker-compose -f docker-compose.yaml down # Stop the currently running services
    - docker-compose -f docker-compose.yaml up -d # Restart the services in detached mode again
    - echo "Application successfully deployed."
    - echo "Application successfully deployed."
