version: "3"
services:
  service1:
    build: ./service1
    deploy:
      replicas: 3
    environment:
      - PORT=5050
    depends_on:
      - service2
    networks:
      - service-network
      - loadbalancing
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket to run docker commands from the containers

  service2:
    build: ./service2
    networks:
      - service-network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8198:80"
      - "8198:81"
    networks:
      - loadbalancing
    depends_on:
      - service1

  apigate:
    build: ./apigate
    container_name: apiGate
    ports:
    networks:
      - loadbalancing
    depends_on:
      - service1

# Network for service communication
networks:
  service-network:
    driver: bridge
  loadbalancing:
    driver: bridge
